on: [pull_request_review, pull_request_review_comment]

jobs:
  echo-chamber:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ github.event.review.body }}'
        echo '${{ github.event.review_comment.body }}' # not defined
