on: [pull_request_review, pull_request_review_comment]

jobs:
  echo-chamber:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ github.event.review.body }}'
        echo '${{ github.event.comment.body }}' # not defined
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
